name: Continous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get flutter dependencies.
        run: flutter pub get

      - name: Statically analyze the Dart code for any errors.
        run: flutter analyze .

      - name: Run widget tests for our flutter project.
        run: flutter test
